config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root 'recipes#index'
  resources :recipes

  get '/recipes/new' => 'articles#new', as: :new_article #new_article_path
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    validates :name, presence: true
    validates :image_url, format: { with: URI::DEFAULT_PARSER.make_regexp, message: "must be a valid URL" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    def index
        @recipes = Recipe.all.order :id
    end

    def new
        @recipe = Recipe.new
    end

    def show
        @recipe = Recipe.find_by(id: params[:id])
    end

    def create
        @recipe = Recipe.new(recipe_params)

        if @recipe.save
            redirect_to recipes_path
        else
            render :new
        end
    end

    def edit
        @recipe = Recipe.find(params[:id])
    end

    def update
        @recipe = Recipe.find(params[:id])
        if @recipe.update(recipe_params)
            redirect_to @recipe
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @recipe = Recipe.find(params[:id])
        @recipe.destroy
        redirect_to recipes_path
    end

    private

    def recipe_params
        params.require(:recipe).permit(:name, :desc, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeBook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='bg-yellow-50 my-auto' style="padding-top: 8%;">
    <header class='bg-white fixed z-50 top-0 left-0 w-full shadow-md transition duration-500'>
    <nav class='flex items-center max-w-screen-xl mx-auto px-6 py-3'>
      <div class='flex flex-grow'>
        <%= link_to recipes_path do %>
          <%= image_tag "recipebooklogo.png", class: "w-36 cursor-pointer" %>
        <% end %>
      </div>
        <div class='flex items-center justify-end space-x-6'>
          <%= link_to 'Add a new recipe', new_recipe_path %>
        </div>
    </nav>
    </header>

    <main>
      <%= yield %>
    </main>
  
  </body>
   
</html>

app/views/recipes/_form.html.erb
<%= form_with model: recipe do |form| %>
  <% if form.object.errors.any? %>
    <div class="bg-red-100 border-l-4 border-red-500 text-red-700 p-4" role="alert">
        <p class="font-bold"><%= pluralize(recipe.errors.count, "error") %>  prohibited this post from being saved:</p>
      <ul class="list-none">
        <% @recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
    <div>
      <p>
        <%= form.label :name %> <br>
        <%= form.text_field :name, class: "w-full" %>
      </p>
    </div>

    <div>
      <p>
        <%= form.label 'Image URL' %><br>
        <%= form.text_field :image_url, class: "w-full" %>
      </p>
    </div>

    <div>
      <p>
        <%= form.label 'Description' %> <br>
        <%= form.text_area :desc, class: "w-full" %>
      </p>
    </div>
    <p>
    <%= form.button "Submit", class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
  </p>
  </div>

  
  </div>
<% end %>

app/views/recipes/edit.html.erb
<section class='mx-auto prose bg-yellow-50'>
<h1>Edit recipe information:</h1>
<%= render "form", recipe: @recipe%>
<br>
<div class='flex-grow items-center gap-4'>
                <div class='flex flex-wrap md:flex-nowrap items-center gap-4 mb-6'>
                <%= link_to "Back to recipes", recipes_path %> |
                <%= link_to "Edit this recipe", edit_recipe_path %> |
                <%= button_to "Delete", @recipe, method: :delete,class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded", data: {turbo_confirm: "Are you sure?"} %>
</div>
</section>

app/views/recipes/index.html.erb
    <section class='my-12 max-w-screen-xl mx-auto px-6'>
        <div class='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10 mt-12'>
            <% @recipes.each do |recipe| %>
        
            <section class='bg-white border border-gray-100 transition transform duration-700 hover:shadow-xl hover:scale-105 p-4 rounded-lg relative'>
                <div class="flex flex-col items-center my-3 space-y-2">
                    <div class='px-6 py-4'>
                        <% if recipe.image_url.present? %>
                        <%= image_tag recipe.image_url, class: "w-full mb-4" %>
                    <% end %>
                        <div class="font-bold text-xl mb-2">
                            <%= link_to recipe.name, recipe_path(recipe), class:"font-medium text-blue-600 dark:text-red-500 hover:underline" %>
                        </div>
                        <p class="text-gray-700 text-base mb-2">
                            <%= recipe.desc %>
                        </p>
                    <%= button_to "Edit Recipe", edit_recipe_path(recipe),method: :get, class: 'bg-transparent hover:bg-red-500 text-red-700 font-semibold hover:text-white py-2 px-4 border border-red-500 hover:border-transparent rounded mb-4' %>
                    </div>
                </div>
            </section>
            
        <% end %>
        </div>
        
    </section>

app/views/recipes/new.html.erb
<section class='mx-auto prose'>
<h1>Add a new recipe</h1>
<!--<%= render partial: "form", locals: {recipe: @recipe} %>  -->
<%= render "form", recipe: @recipe %>

<div>
    <%= link_to "Go back to recipes", recipes_path%>
</div>
</section>

app/views/recipes/show.html.erb
<p style='color:green'><%= notice %></p>

    <div class = 'bg-white border border-gray-100 rounded-lg p-4 mx-auto prose'>
        <div class='flex flex-col md:items-center gap-4 relative p-5'>
            
            <div class=' items-center gap-4'>
                <div class='shrink-0 flex-justify-center' >
                <div class='w-full h-full'>
                            <% if @recipe.image_url.present? %>
                            <%= image_tag @recipe.image_url, class: "max-w-50" %>
                            <% end %>
                 </div>
            </div>

                   <div class='flex items-center mb-4'><p class='text-default-800 text-2xl font-semibold line-clamp-1'><%= @recipe.name%></p></div>

                    <p class='text-base text-default-600 max-w-2xl mb-6'><%= @recipe.desc%></p><br>

                    
                    <div class='flex flex-wrap md:flex-nowrap items-center gap-4 mb-6'>
                        <%= link_to "Back to recipes", recipes_path %> |
                        <%= link_to "Edit this recipe", edit_recipe_path %> |
                        <%= button_to "Delete", @recipe, method: :delete,class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded", data: {turbo_confirm: "Are you sure?"} %>
                    </div>
            </div>

            
        </div>
    </div>
    